### GET request to example server
POST http://localhost:8090/set/loco
Content-Type: text/plain

caitanlakdkerfxkvladsf;kajsdf

###

POST http://localhost:8090/set/secret
Content-Type: text/plain

worked

###

GET http://localhost:8090/get/secret

POST http://localhost:8090/set/arnold
Content-Type: text/plain

latestplus
