### GET request to example server
POST http://localhost:8090/set/loco
Content-Type: text/plain

caitanlakdkerfxkvladsf;kajsdfa

### set anothersecret
POST http://localhost:8090/set/anothersecret
Content-Type: text/plain

worked

###
GET http://localhost:8090/get/loco

###
POST http://localhost:8090/set/arnold
Content-Type: text/plain

latestplus
